// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: mods/etl/protoextr/data.proto

package protoextr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]string      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_mods_etl_protoextr_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_mods_etl_protoextr_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_mods_etl_protoextr_data_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DataList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Data                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataList) Reset() {
	*x = DataList{}
	mi := &file_mods_etl_protoextr_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataList) ProtoMessage() {}

func (x *DataList) ProtoReflect() protoreflect.Message {
	mi := &file_mods_etl_protoextr_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataList.ProtoReflect.Descriptor instead.
func (*DataList) Descriptor() ([]byte, []int) {
	return file_mods_etl_protoextr_data_proto_rawDescGZIP(), []int{1}
}

func (x *DataList) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mods_etl_protoextr_data_proto protoreflect.FileDescriptor

var file_mods_etl_protoextr_data_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6d, 0x6f, 0x64, 0x73, 0x2f, 0x65, 0x74, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x65, 0x78, 0x74, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x65, 0x78, 0x74, 0x72, 0x22, 0x76, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x33, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x65, 0x78, 0x74, 0x72, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x2f, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x65, 0x78, 0x74, 0x72, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x42, 0x14, 0x5a, 0x12, 0x6d, 0x6f, 0x64, 0x73, 0x2f, 0x65, 0x74, 0x6c, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x65, 0x78, 0x74, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_mods_etl_protoextr_data_proto_rawDescOnce sync.Once
	file_mods_etl_protoextr_data_proto_rawDescData = file_mods_etl_protoextr_data_proto_rawDesc
)

func file_mods_etl_protoextr_data_proto_rawDescGZIP() []byte {
	file_mods_etl_protoextr_data_proto_rawDescOnce.Do(func() {
		file_mods_etl_protoextr_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_mods_etl_protoextr_data_proto_rawDescData)
	})
	return file_mods_etl_protoextr_data_proto_rawDescData
}

var file_mods_etl_protoextr_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mods_etl_protoextr_data_proto_goTypes = []any{
	(*Data)(nil),     // 0: protoextr.Data
	(*DataList)(nil), // 1: protoextr.DataList
	nil,              // 2: protoextr.Data.FieldsEntry
}
var file_mods_etl_protoextr_data_proto_depIdxs = []int32{
	2, // 0: protoextr.Data.fields:type_name -> protoextr.Data.FieldsEntry
	0, // 1: protoextr.DataList.data:type_name -> protoextr.Data
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mods_etl_protoextr_data_proto_init() }
func file_mods_etl_protoextr_data_proto_init() {
	if File_mods_etl_protoextr_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mods_etl_protoextr_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mods_etl_protoextr_data_proto_goTypes,
		DependencyIndexes: file_mods_etl_protoextr_data_proto_depIdxs,
		MessageInfos:      file_mods_etl_protoextr_data_proto_msgTypes,
	}.Build()
	File_mods_etl_protoextr_data_proto = out.File
	file_mods_etl_protoextr_data_proto_rawDesc = nil
	file_mods_etl_protoextr_data_proto_goTypes = nil
	file_mods_etl_protoextr_data_proto_depIdxs = nil
}
